name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: japtoo
          password: dckr_pat_dv4uTFuf1IsRHbpayKZk9CGdeds

      - name: Build Docker image
        run: |
          docker build -t kevin-devops-19:${{ github.sha }} .
          docker tag kevin-devops-19:${{ github.sha }} kevin-devops-19:latest

      - name: Push to Docker Hub
        run: |
          docker push kevin-devops-19:${{ github.sha }}
          docker push kevin-devops-19:latest
